name: Marcar Salida GeoVictoria

on:
  schedule:
    - cron: '0 23 * * 1-4'  # Lunes a jueves a las 19:00 (Chile)
    - cron: '0 22 * * 5'    # Viernes a las 18:00 (Chile)
  workflow_dispatch:

jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project with Maven
        run: |
          mvn clean package
          mv target/geo_salida_v2-1.0-SNAPSHOT-jar-with-dependencies.jar target/app.jar

      - name: Build Docker image
        run: docker build -t selenium-job .

      - name: Run Selenium Job
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: docker run -e USERNAME -e PASSWORD selenium-job
